services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mti_attendance_app
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/html
      - ./docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db
    networks:
      - mti_network

  db:
    image: mysql:8.0
    container_name: mti_attendance_db
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: mti_attendance_db
      MYSQL_USER: mti_user
      MYSQL_PASSWORD: mti_pass
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mti_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mti_attendance_phpmyadmin
    restart: unless-stopped
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - mti_network

volumes:
  db_data:

networks:
  mti_network:
    driver: bridge
